name: logger_flutter
description: Flutter extension for logger. Please go there for documentation.
version: 0.7.1
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/logger_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.0.0
  sensors: ^2.0.3